name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Info
      run: rustc --version
    - name: Run tests
      run: cargo test --verbose
    - name: Run SSSE3 tests
      run: export RUSTFLAGS="-C target-feature=+ssse3" && cargo test --verbose
    - name: Run SSE4.1 tests
      run: export RUSTFLAGS="-C target-feature=+sse4.1" && cargo test --verbose
    - name: Run AVX2 tests
      run: export RUSTFLAGS="-C target-feature=+avx2,+bmi2,+bmi,+lzcnt" && cargo test --verbose
